# Generated by Django 3.2.16 on 2024-01-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friend_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
